steps:
# Docker Build
- id: 'build'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-docker.pkg.dev/${PROJECT_ID}/agent-repo/restaurant_agent:$SHORT_SHA', '.']

#Docker Push
- id: 'push'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-docker.pkg.dev/${PROJECT_ID}/agent-repo/restaurant_agent:$SHORT_SHA']

#Agent Deploy with Terraform
- id: 'tf-init'
  name: 'hashicorp/terraform:1.7.0'
  dir: 'terraform'
  entrypoint: 'terraform'
  args: ['init', '-no-color']

- id: 'tf-plan'
  name: 'hashicorp/terraform:1.7.0'
  dir: 'terraform'
  entrypoint: 'terraform'
  args:
    - 'plan'
    - '-no-color' 
    - '-out=tfplan'
    - '-var=project_id=${_PROJECT_ID}'
    - '-var=location=${_LOCATION}'

- id: 'tf-apply'
  name: 'hashicorp/terraform:1.7.0'
  dir: 'terraform'
  entrypoint: 'terraform'
  args:
    - 'apply'
    - '-auto-approve'
    - '-no-color'
    - 'tfplan'
    - '-var=project_id=${_PROJECT_ID}'
    - '-var=location=${_LOCATION}'

options:
  logging: CLOUD_LOGGING_ONLY
