steps:
# Docker Build
- id: 'build'
  name: 'gcr.io/cloud-builders/docker'
  dir: 'reservation_agent'
  args: ['build', '-t', 'us-docker.pkg.dev/${PROJECT_ID}/agent-repo/reservation_agent:$SHORT_SHA', '.']

#Docker Push
- id: 'push'
  name: 'gcr.io/cloud-builders/docker'
  dir: 'reservation_agent'
  args: ['push', 'us-docker.pkg.dev/${PROJECT_ID}/agent-repo/reservation_agent:$SHORT_SHA']

#Agent Deploy with Terraform
- id: 'tf-init'
  name: 'hashicorp/terraform:1.7.0'
  dir: 'terraform'
  entrypoint: 'terraform'
  args:
    - 'init'
    - '-no-color'
    - '-var=project_id=${_PROJECT_ID}'
    - '-var=location=${_LOCATION}'
    - '-var=image_tag=${SHORT_SHA}'
    - '-var=agent_name=reservation_agent'
    - '-var=agent_display_name=Reservation Agent Runtime'
    - '-var=agent_description=BYOC Agent for reserving tables at restaurants'
    - '-var=agent_framework=a2a'

- id: 'tf-plan'
  name: 'hashicorp/terraform:1.7.0'
  dir: 'terraform'
  entrypoint: 'terraform'
  args:
    - 'plan'
    - '-no-color' 
    - '-out=tfplan'
    - '-var=project_id=${_PROJECT_ID}'
    - '-var=location=${_LOCATION}'
    - '-var=image_tag=${SHORT_SHA}'
    - '-var=agent_name=reservation_agent'
    - '-var=agent_display_name=Reservation Agent Runtime'
    - '-var=agent_description=BYOC Agent for reserving tables at restaurants'
    - '-var=agent_framework=a2a'

- id: 'tf-apply'
  name: 'hashicorp/terraform:1.7.0'
  dir: 'terraform'
  entrypoint: 'terraform'
  args:
    - 'apply'
    - '-auto-approve'
    - '-no-color'
    - 'tfplan'

# Extract deployed Reasoning Engine Resource Name
- id: 'tf-output'
  name: 'hashicorp/terraform:1.7.0'
  dir: 'terraform'
  entrypoint: 'sh'
  args:
    - '-c'
    - 'terraform output -raw reasoning_engine_resource_name > /workspace/reasoning_engine_resource_name.txt'

# Register or update A2A Service in Google Cloud Agent Registry
- id: 'register-a2a-service'
  name: 'us-docker.pkg.dev/${PROJECT_ID}/agent-repo/reservation_agent:$SHORT_SHA'
  dir: '/app'
  entrypoint: 'python'
  args:
    - 'register_a2a_service.py'
    - '--project-id=${_PROJECT_ID}'
    - '--location=${_LOCATION}'
    - '--re-file=/workspace/reasoning_engine_resource_name.txt'

options:
  logging: CLOUD_LOGGING_ONLY
